Repository abhisek247767/PeopleHub-Backend, pull requests merged in 2025-08, with the labels that each got.

#29 Made and edited the schemas of projects,employees and user.
  src/controllers/EmployeeController.js
  src/controllers/ProjectController.js
  src/controllers/userController.js
  src/index.js
  src/middleware/authMiddleware.js
  src/models/Employee.js
  src/models/Project.js
  src/models/index.js
  src/models/userSchema.js
  src/routes/employee.js
  src/routes/project.js
  src/routes/user.js
  src/services/EmployeeService.js
  src/services/ProjectService.js
  src/services/index.js
Labels: gssoc25, level 3

#28 Introduce service layer for authentication: Improved maintainability
  src/controllers/authController.js
  src/services/authService.js
Labels: good first issue, gssoc25, level 3

#35 Revert "Introduce service layer for authentication: Improved maintainability"
  src/controllers/authController.js
  src/services/authService.js
Labels: gssoc25, level 1

#38 Enhanced Dashboard: Employee & Project Stats
  src/controllers/dashboardController.js
  src/index.js
  src/routes/dashboard.js
  src/services/DashboardService.js
  src/services/index.js
Labels: good first issue, gssoc25, level 2

#39 Origin/development
  src/controllers/dashboardController.js
  src/index.js
  src/routes/dashboard.js
  src/services/DashboardService.js
  src/services/index.js
Labels: gssoc25, level 1

#41 Update README.md
  README.md
Labels: good first issue, gssoc25, level 1
