Repository abhisek247767/PeopleHub-Backend, pull requests merged in 2025-07, with the labels that each got.

#3 Add fetchAccountData route and update cookie settings in loginUser
  src/controllers/authController.js
  src/routes/auth.js
Labels: gssoc25, level 3

#7 Filename error in user.js
  src/routes/user.js
Labels: gssoc25, level 1

#14 #12 Forgot-passowrd and email verification added
  README.md
  src/controllers/authController.js
  src/models/userSchema.js
  src/routes/auth.js
  src/services/mailService.js
Labels: gssoc25
